gp/core/views.py
from flask import render_template, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')


@core.route('/info')
def info():
    #! crate info.html file
    return render_template('info.html')


@core.route('/support')
def support():
    return render_template('support.html')


@core.route('/tremsofuser')
def tremsofuser():
    return render_template('tremsofuser.html')

gp/doctors/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from gp import db
from gp.models import Doctor, Patient ,ScanRequest,PatientInfo
from gp.doctors.forms import RegistrationForm,LoginForm,SubmitRequestForm
from gp.doctors.picture_handler import add_profile_pic

doctors = Blueprint('doctors',__name__)

# register
@doctors.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = Doctor(email=form.email.data,
                      username=form.username.data,
                      password=form.password.data,
                      specialization=form.specialization.data,)  # Adding specialization

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('doctors.login'))

    return render_template('register.html', form=form)




# login
@doctors.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = Doctor.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)
# logout
@doctors.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("core.index"))

@doctors.route("/request_list")
@login_required
def request_list():
    # Query to join ScanRequest and PatientInfo, filter by unprocessed requests,
    # and order by scan_date in descending order
    requests = db.session.query(ScanRequest, PatientInfo) \
        .join(PatientInfo, ScanRequest.patient_id == PatientInfo.patient_id) \
        .filter(ScanRequest.requests == False) \
        .order_by(ScanRequest.scan_date.desc()) \
        .all()
    forms = {request.ScanRequest.id: SubmitRequestForm() for request in requests}
    return render_template("request_list.html", requests=requests, forms=forms)

gp/patients/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from gp import db
from gp.models import Doctor, Patient,ScanRequest,PatientInfo
from gp.patients.forms import AddPatientForm, SearchAddPatientForm, UpdateUserForm,ToProfileForm,ToResultForm,PatientInfoForm,RequestSearchForm,RequestForm
from gp.patients.picture_handler import add_profile_pic
from datetime import datetime
import pytz

def get_ksa_time():
    utc_time = datetime.utcnow()
    ksa_timezone = pytz.timezone('Asia/Riyadh')
    ksa_time = utc_time.replace(tzinfo=pytz.utc).astimezone(ksa_timezone)
    return ksa_time

patients = Blueprint("patients", __name__)


@patients.route("/add_patient", methods=["GET", "POST"])
@login_required
def add_patient():
    form = AddPatientForm()
    patient_id = request.args.get('patient_id', None)
    request_id = request.args.get('request_id', None)  # Get the request_id from query parameters

    if patient_id:
        form.patient_id.data = patient_id
        form.patient_id.render_kw = {'readonly': True}

    if form.validate_on_submit():
        if form.brain_img.data:
            patient_info = PatientInfo.query.filter_by(patient_id=form.patient_id.data).first()
            if not patient_info:
                flash('No existing patient info found for this ID.', 'warning')
                return render_template("add_patient.html", form=form)

            pic = add_profile_pic(form.brain_img.data, form.patient_id.data)
            patient = Patient(
                patient_id=form.patient_id.data,
                brain_img=pic,
                date=get_ksa_time(),  # Adjusted to KSA time
                classifier="gg",
                accuracy=69.69,
                doctor_id=current_user.id
            )
            db.session.add(patient)

            # Update the scan request status if a request_id was provided
            if request_id:
                scan_request = ScanRequest.query.get(int(request_id))
                if scan_request:
                    scan_request.requests = True
                    db.session.commit()
                    flash('Scan added and request marked as completed.', 'success')
                else:
                    flash('No matching scan request found.', 'error')

            return redirect(url_for("patients.result", username_id=form.patient_id.data, pic=pic))
        else:
            flash('Error: Image file is required.', 'danger')

    return render_template("add_patient.html", form=form)





            ####################################################
                # AddPatientForm from forms.py
                
                # patient_id = StringField("Patient ID:", validators=[DataRequired()])
                # brain_img = FileField("Choose a file", validators=[FileAllowed(["jpg", "png"])])
                # date = DateTimeField("Date of Scan", format='%Y-%m-%d %H:%M', validators=[DataRequired()], render_kw={"placeholder": "Format: YYYY-MM-DD HH:MM"})
                # classifier = StringField("Classification :", validators=[DataRequired()])
                # accuracy = FloatField("Accuracy of Analysis (%)", validators=[DataRequired()])
                # doctor_id = IntegerField("Doctor ID:", validators=[DataRequired()], render_kw={'readonly': True})
                # submit = SubmitField("Submit")
                
            #########################################################
            # Add a new scan record to the scan history
            # new_scan = ScanRequest(
            #     doctor_name=current_user.username,  # Assuming current user is the doctor adding the patient
            #     result="Initial scan result",
            #     patient_id=patient.id
            # )
            # db.session.add(new_scan)
            # db.session.commit()
@patients.route("/search_patient", methods=["GET", "POST"])
@login_required
def search_patient():
    form = SearchAddPatientForm()
    if form.validate_on_submit():
        username_id = form.patient_id.data
        return redirect(url_for("patients.profile", username_id=username_id))
    return render_template("search_patient.html", form=form)


@patients.route("/profile/<username_id>", methods=["GET", "POST"])
@login_required
def profile(username_id):
    # Query the PatientInfo based on patient_id
    patient_info = PatientInfo.query.filter_by(patient_id=username_id).first()
    if not patient_info:
        flash("No patient information available.")
        return redirect(url_for("patients.add_patient_info"))

    # Query all related Patient records and order them by date in ascending order
    patients = Patient.query.filter_by(patient_id=username_id).order_by(Patient.date.desc()).all()
    if not patients:
        flash("No scans found for this patient.")
        return redirect(url_for("patients.add_patient")) 

    # Create a map of doctors for each patient
    doctor_map = {patient.id: Doctor.query.get(patient.doctor_id) for patient in patients if patient.doctor_id}

    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.brain_img.data:
            pic = add_profile_pic(form.brain_img.data, username_id)
            for patient in patients:
                patient.brain_img = pic
        if patient_info:
            patient_info.username = form.username.data
        db.session.commit()
        flash("Profile Updated Successfully!")
        return redirect(url_for("patients.profile", username_id=username_id))

    elif request.method == "GET" and patient_info:
        form.username.data = patient_info.username

    form2 = ToResultForm()
    if form2.validate_on_submit():
        return redirect(url_for("patients.result", username_id=username_id))
    
    return render_template("profile.html", patient_info=patient_info, patients=patients, doctor_map=doctor_map, form=form, form2=form2)




@patients.route("/result/<username_id>", methods=["GET", "POST"])
@login_required
def result(username_id):
    pic = request.args.get('pic', None)  # Get pic parameter from query string

    # Query for the latest patient record based on the 'date' field
    patient = Patient.query.filter_by(patient_id=username_id).order_by(Patient.date.desc()).first()
    if not patient:
        flash("No patient found with the given ID.", "warning")
        return redirect(url_for("patients.add_patient"))

    # Continue with the rest of the existing code
    doctor = Doctor.query.filter_by(id=patient.doctor_id).first()
    patient_info = PatientInfo.query.filter_by(patient_id=username_id).first()
    if not patient_info:
        flash("No personal information found for this patient.", "warning")
        return redirect(url_for("patients.add_patient_info"))

    form = ToProfileForm()
    if form.validate_on_submit():
        return redirect(url_for("patients.profile", username_id=username_id))

    # Pass both patient and patient_info objects to the template, along with the pic
    return render_template("results.html", patient=patient, doctor=doctor, patient_info=patient_info, pic=pic, form=form)



@patients.route("/patient_info", methods=["GET", "POST"])
@login_required
def patient_info():
    form = PatientInfoForm()
    if form.validate_on_submit():
        print("hello")
        patient_info = PatientInfo(
            username=form.username.data,
            patient_id=form.patient_id.data,
            gender=form.gender.data,
            age=form.age.data
            # PatientInfoForm from forms.py
            # username = StringField("Patient Name: ", validators=[DataRequired()])
            # patient_id = StringField("Patient ID: ", validators=[DataRequired()])
            # gender = SelectField('gender', choices=[('Male', 'Male'), ('Female', 'Female')])
            # age = StringField("Age:", validators=[DataRequired()])
        )
        db.session.add(patient_info)
        db.session.commit()
        return redirect(url_for("patients.request_scan"))
    else:
        print("form is not working properly")
    return render_template("patient_info.html", form=form)

@patients.route("/request", methods=["GET", "POST"])
@login_required
def request_scan():
    search_form = RequestSearchForm()
    request_form = RequestForm()

    if search_form.validate_on_submit() and search_form.submit.data:
        patient_info = PatientInfo.query.filter_by(patient_id=search_form.patient_id.data).first()
        if patient_info:
            return redirect(url_for("patients.request_scan", patient_id=patient_info.patient_id))  # Pass patient_id as query parameter
        else:
            flash("No patient found with this ID.", "warning")

    # Checking if 'patient_id' is in query string for continuity in form submissions
    patient_id = request.args.get('patient_id')
    if patient_id:
        patient_info = PatientInfo.query.filter_by(patient_id=patient_id).first()
        if request_form.validate_on_submit() and request_form.submit.data:
            if patient_info:
                new_request = ScanRequest(patient_id=patient_info.patient_id, doctor_id=current_user.id)
                db.session.add(new_request)
                db.session.commit()
                flash("Scan request submitted successfully.", "success")
                return redirect(url_for("patients.request_scan"))
            else:
                flash("Failed to submit request. Patient not found.", "error")
        return render_template("request_scan.html", search_form=search_form, request_form=request_form, patient_info=patient_info)
    
    return render_template("request_scan.html", search_form=search_form, request_form=request_form)

gp/templates/add_patient.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Add any necessary meta tags, title, and links to CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
</head>

<body>

    <div class="container3">
        <img class="rec" src="{{ url_for('static', filename='images/Xray1.jpg') }}" width="100%" height="100%">
    </div>

    <div class="rectangle1">
        <label>
            <h3>Add Patient MRI Scans</h3>
        </label><br>
        <div class="rectangle2">
            <form id="uploadForm" method="POST" action="" enctype="multipart/form-data"
                onsubmit="return validateLogin()">
                {{ form.hidden_tag() }}
                <div>
                    <p>{{ form.patient_id.label }}</p>{{ form.patient_id }}
                </div>
        </div>
        <div class="rectangle3">
            <!-- Drop area for uploading images -->
            <label id="drop-area">
                <!-- <input type="file" accept="image/*" id="input-file" hidden onchange="displayFileName(this)"/> -->
                {{ form.brain_img(id="input-file", hidden=true, onchange="displayFileName(this)") }}
                <div id="img-view">
                    <img id="preview-image" src="{{ url_for('static', filename='images/icon_uplaod.webp') }}">
                    <div class="file-upload">
                        <p id="file-name-label">{{ form.brain_img.label}}</p>
                    </div>
                </div>
            </label>
        </div>

        <script>
            // Function to display the uploaded file name for the brain_img input field
            function displayFileName(input) {
                const fileNameLabel = document.getElementById('file-name-label');
                const targetInput = document.getElementById('{{form.brain_img}}'); // Assuming 'brain_img' is the ID of the input field
                if (input.files.length > 0) {
                    fileNameLabel.textContent = input.files[0].name;
                    targetInput.value = input.files[0].name; // Set the value of the target input field
                } else {
                    fileNameLabel.textContent = 'No file chosen';
                    targetInput.value = ''; // Clear the value of the target input field
                }
            }
        </script>
        <label>{{ form.submit() }}</label>
        </form>
    </div>



    <script src="{{ url_for('static', filename='js/JS.js') }}"></script>

</body>

</html>

{% endblock %}

gp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
  <script type="text/javascript" src="{{ url_for('static', filename='js/JS.js') }}"></script>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/style.css') }}">
</head>
<body>
  <div class="top">
    <img class="img3" src="{{ url_for('static', filename='images/Logo_black.png') }}" />
    <p>Alzheimer Diagnosis System</p>
    <a href="{{ url_for('core.index') }}">Home</a>
    {% if current_user.is_authenticated %}
      <a href="{{ url_for('patients.search_patient')}}">Patient File Search</a>
      {% if current_user.specialization == "Radiologist" %}
        <a href="{{ url_for('patients.add_patient')}}">Add Patient</a>
        <a href="{{ url_for('doctors.request_list')}}">Request List</a>
      {% endif %}
      {% if current_user.specialization == "Neurologist" %}
        <a href="{{ url_for('patients.request_scan')}}">Request Scan</a>
      {% endif %}
      <a href="{{ url_for('patients.patient_info')}}">Patient Info</a>
      <a href="{{ url_for('doctors.logout')}}">Log out</a>
    {% else %}
      <a href="{{ url_for('doctors.login')}}">Log in</a>
      <a href="{{ url_for('doctors.register')}}">Register</a>
    {% endif %}
  </div>
  {% block content %}

  {% endblock %}
  <footer>
    <a href="{{ url_for('core.support')}}">Support</a>
    <a href="{{ url_for('core.tremsofuser')}}">Terms of use</a>
    <a href="{{ url_for('core.info') }}">About us</a>
  </footer>
  <script src="{{ url_for('static', filename='js/JS.js') }}"></script>
</body>
</html>

gp/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container3">
  <img class="rec" src="{{ url_for('static', filename='images/Xray.jpg') }}" width="100%">
  <div class="textInImg">
    <h1>AI Diagnosis <br>System</h1> <br><br>
    <p>welcome to our website,
      dedicated to revolutionizing Alzheimer's disease Diagnosis.<br> We harness the power
      of artificial intelligence to provide early and accurate detection.</p>
  </div>
</div>
<div class="card">
  <img src="{{ url_for('static', filename='images/card11.png') }}" width="150px">
</div>
<div class="card">
  <img src="{{ url_for('static', filename='images/card22.png') }}" width="150px">
</div>
<div class="card">
  <img src="{{ url_for('static', filename='images/card33.png') }}" width="150px">
</div>

{% endblock %}

gp/templates/info.html
{% extends "base.html" %}
{% block content %}

<div class="about">
    <br>
    <h2>Use of Website Content:</h2>
    <div class="about1">
        <p>
            Welcome to our website, where we are dedicated to advancing Alzheimer's disease diagnosis through AI and image classification. Our team of researchers is committed to revolutionizing the field by leveraging AI algorithms and deep learning models to analyze MRI scans. Our innovative approach aims to detect early signs of Alzheimer's, improve accuracy, and provide personalized treatment strategies. By making the diagnostic process more patient-friendly and accessible, we offer hope for earlier detection and better management of this challenging condition. Join us on this transformative journey to make a significant impact on Alzheimer's disease.
        </p>
    </div>
</div>

{% endblock %}

gp/templates/login.html
{% extends "base.html" %}
{% block content %}

<div class="containerMain">
    <div class="container">
      <img class="img1" src="{{ url_for('static', filename='images/img1.png') }}">
    </div>

    <div class="containerLogin"> 
        <img class="img2" src="{{ url_for('static', filename='images/Project_Logo_PNG.png') }}">
        <h2 class="welcome">Welcome to Alzheimer <br>Diagnosis System</h2>

        <form method="POST" onsubmit="return validateLogin();">
            {{ form.hidden_tag() }}
            {{ form.email.label }}{{ form.email(class="logEmail") }}<br>
            {{ form.password.label }}{{ form.password(class="logPass") }}<br>
            {{ form.submit() }}
        </form>
    </div>
</div>

{% endblock %}

gp/templates/patient_info.html
{% extends "base.html" %}
{% block content %}
<style>

    .rect1 {
        margin-top: 1%;
        margin-left: 35%;
        margin-bottom: 10%;
        border-radius: 10px;
        border: 5px solid #aba38e;
        width: 35%;
        height: 80%;
        background-color: #f8f8ec;
        text-align: center;
      }
      .rect2 {
        width: 60%;
        height: 60%;
        background: #d8d8d8;
        border-radius: 10px;
        border: #566c6e dashed 3px;
        margin: 5% auto; /* Center horizontally */
        display: flex;
        flex-direction: column;
        align-items: center;
    }
      
      .rect2 input[type="number"] {
        margin-top:9%;
        margin-bottom: 5%;
        border-radius: 6px;
        border-color: #000;
        font-size: 25px;
        width: 35%;
        background-color: #ddd5bf;
      }
      
      .rect2 input[type="text"] {
        margin-top:9%;
        margin-bottom: 5%;
        border-radius: 6px;
        border-color: #000;
        font-size: 25px;
        width: 39%;
        background-color: #ddd5bf;
      }
      .rect2 select{
        margin-top:9%;
        margin-bottom: 5%;
        border-radius: 6px;
        border-color: #000;
        font-size: 20px;
        width: 39%;
        background-color: #ddd5bf;
      }
      
      .rect2 p {
        margin-left:5%;
        margin-top: 6%;
        color: #3e695f;
        display: inline-block;
        left: 0px;
      }
      
      .rect1 h3 {
        margin-top: 3%;
        color: #852424;
      }
      .rect1 input[type="submit"] {
        font-size: 16px;
        padding: 1%;
        width: 20%;
        margin-top: 5%;
        border-radius: 10px;
        cursor: pointer;
        border-color: #d5cbb0;
        background-color: #d5cbb0;
      }
</style>


<div class="container3">
    <img class="rec" src="{{ url_for('static', filename='images/Xray1.jpg') }}" width="100%" height="100%">
</div>

<div class="rect1">
    <label>
        <h3>Add Patient Information</h3>
    </label><br>
    <div class="rect2">
        <form id="patientinfo" method="POST" action="" enctype="multipart/form-data"
            onsubmit="return validateLogin()">
            {{ form.hidden_tag() }}
            <div>
                <p>{{form.username.label}}  </p>{{form.username}}
            </div>
            <div>
                <p>{{form.patient_id.label}}&nbsp;&nbsp;&nbsp; </p>{{form.patient_id}}
            </div>
            <div>
                <p>{{form.gender.label}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>{{form.gender}}
            </div>
            <div>
                <p>{{form.age.label}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>{{form.age}}
            </div>            
    </div>
    <label>{{ form.submit() }}</label>
    </form>
</div>

{% endblock %}

gp/templates/profile.html
{% extends "base.html" %}

{% block content %}

<style>
    .card {
        display: flex;
        justify-content: space-between; /* Ensures space between content and image */
        /* align-items: center; Vertically center content */
        background: #f9f9f9;
        border: 1px solid #ddd;
        margin-top: 10px;
        margin-left: 5%;
        margin-right: 5%;
        padding: 15px;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    }
    .card-info {
        flex: 1; /* Takes up remaining space */
    }
    .card-image {
        flex-basis: 200px; /* Width of the image container */
        text-align: center; /* Center the image */
    }
    .card-header {
        background: #e9ecef;
        border-bottom: 1px solid #ddd;
        padding: 10px 15px;
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
        font-weight: bold;
    }
    .card-body img {
        width: 100%; /* Adjust based on your need */
        max-width: 200px;
        height: auto;
    }
    .image-container1 img.result-image1 {
        cursor: pointer;
        transition: transform 0.2s ease;
    }
    .image-container1:hover img.result-image1 {
        transform: scale(1.05);
    }
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        padding-top: 100px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0,0,0,0.4);
    }
    .modal-content {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
    }
    .close {
        position: absolute;
        top: 15px;
        right: 35px;
        color: #f1f1f1;
        font-size: 40px;
        font-weight: bold;
        transition: 0.3s;
    }
    .close:hover,
    .close:focus {
        color: #bbb;
        text-decoration: none;
        cursor: pointer;
    }
</style>

<div class="container3">
    <img class="Xray1" src="{{ url_for('static', filename='images/Xray1.jpg') }}" width="100%">
</div>

<div class="PatientInf">
    <div><h3>Patient Information</h3></div>
    <p>Patient Name: {{ patient_info.username }}</p>
    <p>Patient ID: {{ patient_info.patient_id }}</p>
    <p>Gender: {{ patient_info.gender }}</p>
    <p>Age: {{ patient_info.age }}</p>
</div>

<div class="history">
    <h4>Scan History</h4>
    <div class="card-container">
        {% for patient in patients | sort(attribute='date', reverse=true) %}
            <div class="card">
                <div class="card-info">
                    <div class="card-header">Scan Date: {{ patient.date.strftime('%Y/%m/%d %H:%M') }}</div>
                    <div class="card-body">
                        <ul class="info-list">
                            <li>Doctor Name: {{ doctor_map[patient.id].username if patient.id in doctor_map else 'Unknown Doctor' }}</li>
                        </ul>
                    </div>
                </div>
                <div class="card-image">
                    <!-- Clickable image redirecting to the result page -->
                    <a href="{{ url_for('patients.result', username_id=patient.patient_id) }}">
                        <img src="{{ url_for('static', filename='profile_pics/' + patient.brain_img) }}" height="150" width="150" alt="Scan image of {{ patient_info.username }}">
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

gp/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="container0">
    <img class="regimg" src="{{ url_for('static', filename='images/green.png') }}" >
    <div class="inimg">
        <div class="inimg_con">
            <h2 class="welcome">Welcome to Alzheimer Diagnosis System</h2>
            <form method="POST">
                {{ form.hidden_tag() }}
                <p>{{ form.email.label }}</p>{{ form.email }}<br>
                <p>{{ form.username.label }}</p>{{ form.username }}<br>
                <p>{{ form.specialization.label }}</p>
                <select name="specialization" required>
                    <option value="" disabled selected>Select...</option>
                    <option value="Radiologist">Radiologist</option>
                    <option value="Neurologist">Neurologist</option>
                </select><br>
                <p>{{ form.password.label }}</p>{{ form.password }}<br>
                <p>{{ form.pass_confirm.label }}</p>{{ form.pass_confirm }}<br>
                
                {{ form.submit() }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

gp/templates/request_list.html
{% extends "base.html" %}

{% block content %}

<br>
<style>
    .rectangleRs {
        padding-bottom: 2%;
        margin-top: 15%;
        margin-left: 15%;
        margin-bottom: 20%;
        border-radius: 10px;
        border: 5px solid #aba38e;
        width: 70%;
        background-color: #f8f8ec;
        text-align: center;
        color: black;
    }
    .rectangleRs button[type="submit"] {
        font-size: 25px;
        padding: 1%;
        width: 70%;
        border-radius: 10px;
        cursor: pointer;
        border-color: #D5CBB3;
        background-color: #d5cbb0;
    }
      table {
        width: 100%;
      }
      td {
        height: 50px;
        vertical-align: center;
      }
      th{
        height: 70px;
        vertical-align: top;

      }

      h2{
        margin-top:1%;
        margin-bottom:5%;
      }
      
</style>
<div class="rectangleRs">
    <div class="container">
        <h2>Scan Requests</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Request ID</th>
                    <th>Request Date</th>
                    <th>Patient ID</th>
                    <th>Patient Name</th>  <!-- Added column for Patient Name -->
                    <th>Doctor ID</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for request, patient_info in requests %}
                <tr>
                    <td>{{ request.id }}</td>
                    <td>{{ request.scan_date.strftime('%Y-%m-%d %H:%M') }}</td>
                    <td>{{ request.patient_id }}</td>
                    <td>{{ patient_info.username }}</td>  <!-- Displaying Patient Name -->
                    <td>{{ request.doctor_id }}</td>
                    <td>{{ 'Pending' if not request.requests else 'Completed' }}</td>
                    <td>
                        <form action="{{ url_for('patients.add_patient') }}" method="GET">
                            <input type="hidden" name="request_id" value="{{ request.id }}">
                            <input type="hidden" name="patient_id" value="{{ request.patient_id }}">
                            <button type="submit" class="btn btn-primary">Add Scan</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

gp/templates/request_scan.html
{% extends "base.html" %}
{% block content %}
<br>
<style>
    .rectangleRs {
        padding-bottom:2%;
        margin-top: 15%;
        margin-left: 35%;
        margin-bottom: 22.5%;
        border-radius: 10px;
        border: 5px solid #aba38e;
        width: 35%;
    
        background-color: #f8f8ec;
        text-align: center;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        color:black;
      }
      .rectangleRs div{
        margin-top:2%;
        
      }

      .rectangleRs input[type="text"] {
        border-radius: 6px;
        font-size: 16px;
        padding: 1%;
        width: 30%;
        font-size: 20px;
      }
      .rectangleRs input[type="submit"] {
        font-size: 16px;
        padding: 1%;
        width: 15%;
        margin-top: 20px;
        border-radius: 10px;
        cursor: pointer;
        border-color: #d5cbb0;
        background-color: #d5cbb0;
        /* margin-buttom:15%; */
      }
</style>
<div class="rectangleRs">
    <div class="container">
        <!-- Flash messages display area -->
        <!-- {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %} -->
        <div><h3>Search for Patient File</h3></div>
        <form method="POST">
            {{ search_form.hidden_tag() }}
           <div class"patientid"> {{ search_form.patient_id.label }} {{ search_form.patient_id() }}
            &nbsp;&nbsp; {{ search_form.submit() }}</div>
        </form>
    
        {% if patient_info %}
            <div>
                <h2>Patient Information</h2>
                <p>Name: {{ patient_info.username }}</p>
                <p>ID: {{ patient_info.patient_id }}</p>
                <p>Age: {{ patient_info.age }}</p>
                <p>Gender: {{ patient_info.gender }}</p>
                
                <form method="POST">
                    {{ request_form.hidden_tag() }}
                    {{ request_form.submit() }}
                </form>
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}